HIPS/autograd

autograd/numpy/numpy_grads.py
tests/test_numpy.py
tests/test_systematic.py

Reverts HIPS/autograd#61
It needs more work!

Revert e827c9f3bb380cbc7dcdfcaf7526a55795907210

---

autograd/core.py

Check out this mechanism for improving error messages (inspired by #58 and student confusion in CS281). Revisions and more additions to the `common_errors` table are welcome. Thoughts?

Better error messages

---

setup.py

Someone had a bug on Windows. This code isn't providing enough value to justify the possibility of more weird edge cases.

remove extension modules

---

autograd/convenience_wrappers.py
tests/test_wrappers.py

This gives the behaviour that I was hoping for. Now works for when fun
is a function of a matrix or higher order tensor (of any order).

Change dot to tensor dot in convenience_wrappers

---

autograd/__init__.py
autograd/convenience_wrappers.py
tests/test_wrappers.py

This would also be useful I think.

Add jacobian vector product

---

autograd/numpy/numpy_grads.py
tests/test_systematic.py

I implemented ```Numpy.inner()```.

Add Numpy.inner()

---

autograd/numpy/numpy_grads.py
tests/test_systematic.py

I solved https://github.com/HIPS/autograd/issues/112

Broadcasting einsum() and matmul()

---

setup.py

Library dependencies updates to solve https://github.com/HIPS/autograd/issues/130 and https://github.com/HIPS/autograd/issues/131 .

Update library dependencies

---

autograd/numpy/numpy_wrapper.py

Changed from ValueErrpr to ValueError.

Typo: ValueErrpr

---

autograd/numpy/linalg.py
tests/test_linalg.py

I've tidied up the `check_implemented` function within `make_grad_norm`, implemented the derivative of the nuclear norm (including tests) and added second derivative to the svd testing.

Implement grad of nuclear matrix norm

---

.travis.yml
autograd/__init__.py
autograd/convenience_wrappers.py
autograd/core.py
autograd/numpy/numpy_extra.py
autograd/reverse_mode.py
autograd/util.py
docs/tutorial.md
setup.py

@mattjj do you think this is a good idea? should we go for further re-factoring?
I still need to fix one or two bugs which are causing a few of the tests to fail, then move forward mode code out of core.py and clean up now redundant code from core.py.

Separate reverse mode into a different module

---

autograd/scipy/stats/multivariate_normal.py
examples/gaussian_process.py
tests/test_scipy.py

Fixes https://github.com/HIPS/autograd/issues/201

Add mvn vjp allowsingular optional arg

---

autograd/numpy/fft.py
tests/test_fft.py

This PR adds real-complex FFT gradient back propagation and tests, according to the autograd convention of complex gradients.

Add real-complex FFT gradients and tests.

---

autograd/util.py

I added the primitive type constructors `make_tuple`, `make_list` and `make_dict` to the `unflatten_func` returned by `util.flatten` so that the flattening/unflattening process can be differentiated through in cases like #198 where these constructors are required.

added make_dict, make_list, make_tuple to unflatten_func in util.flatten

---

autograd/numpy/linalg.py

Just been running coverage checks and coming across obvious typos. This is one of them.

[Spring cleaning] Remove unnecessary norm 'check_implemented'

---

examples/variational_autoencoder.py

Print the value of the ELBO (free energy) on the test set every 100 iterations.

Add test set ELBO evaluation to vae example

---

autograd/__init__.py
autograd/convenience_wrappers.py
tests/test_wrappers.py

Fixes #218 
Will add tests in future commits.

feat: add "value_and_multigrad" convenience wrapper

---

autograd/core.py

Cleaner IMO and one less line of code.

Use pop(node) instead of del outgrads[node]

---

README.md
examples/tanh.py

Feel free to close if you prefer the old way, but after Matt's simplification, I think this is more readable.  It's also more obvious when skimming that we're taking grads of grads.

Simplify readme and tanh example using nested grads

---

autograd/container_types.py
autograd/numpy/numpy_extra.py
autograd/util.py
tests/test_flatten.py

separate util.flatten from vspace.flatten, reverting #232

---

.gitignore
benchmarks/bench_core.py
benchmarks/bench_rnn.py
benchmarks/bench_util.py

Also reorganise existing benchmarks and add .asv/ directory to
.gitignore.

Add core benchmarks

---

autograd/container_types.py
autograd/convenience_wrappers.py
autograd/core.py
autograd/numpy/linalg.py
autograd/numpy/numpy_extra.py
autograd/numpy/numpy_grads.py
autograd/scipy/signal.py
autograd/util.py
examples/bayesian_neural_net.py
examples/natural_gradient_black_box_svi.py
tests/test_binary_ops.py
tests/test_core.py
tests/test_primitives.py
tests/test_wrappers.py

Also fix optimizers import in bbsvi example

Remove unused imports

---

autograd/numpy/numpy_vspaces.py

I think this should be len rather than sum.

Correct numpy vspace ndim

---

autograd/container_types.py
autograd/core.py
autograd/numpy/numpy_jvps.py
autograd/numpy/numpy_vspaces.py
autograd/test_util.py
tests/numpy_utils.py
tests/test_fft.py
tests/test_linalg.py
tests/test_numpy.py
tests/test_scipy.py

Here we go... I haven't quite ported all of the jvps that I wrote, specifically the scipy ones aren't done yet and maybe one or two other primitives. They wouldn't take too long but I'm gonna leave them for now I think until someone actually needs to use them.
Perhaps @mattjj's make_jvp should be renamed to make_jvp_staged, since that's what it does, and the pure forward mode make_jvp is currently not staged.

Dougal dev fwd mode

---

autograd/numpy/numpy_jvps.py
autograd/numpy/numpy_vjps.py
autograd/numpy/numpy_wrapper.py

Inspired by the beautiful new flatten implementation...

Improve np.array implementation, fixes #255

---

autograd/numpy/numpy_grads.py
tests/test_binary_ops.py

Very straightforward. Added the gradient of the hypothenuse and added a unittest.
I could offcourse replace np.hypot(x, y) with np.sqrt(x**2 + y**2) since autograd has no trouble with that expression. However I've used np.hypot in a bunch of places so this seemed like a nicer solution.

Added the gradient of the hypothenuse and made a testing function for it

---

autograd/core.py
autograd/differential_operators.py
autograd/test_util.py
tests/test_wrappers.py

I think `make_jvp` should return the function value as well, like this. Thoughts @j-towns and @dougalm?

make_jvp(f)(g) should return the function value as well

---

autograd/__init__.py
autograd/core.py
tests/test_binary_ops.py
tests/test_wrappers.py

add primitive wrapper backward-compatible methods and deprecation warnings

---

autograd/numpy/numpy_jvps.py
autograd/numpy/numpy_vjps.py
tests/test_binary_ops.py

Added the gradient of arctan2 for jvp and vjp. Also included a binary ops test for the arctan2 function.

Added the gradient for arctan2

---

docs/tutorial.md

@mattjj just a minor patch to the tutorial, nothing more than that. Merry Christmas and Happy New Year! :smile:

Minor patch to tutorial - Py3k compatibility.

---

autograd/scipy/special.py
tests/test_scipy.py

Functions:
i0, Modified Bessel function of order 0.
i1, Modified Bessel function of order 1.
iv, Modified Bessel function of the first kind of real order.
Source: http://functions.wolfram.com/Bessel-TypeFunctions/BesselI/20/ShowAll.html

Adding faster versions of common Bessel functions in scipy.special

---

autograd/scipy/stats/norm.py
tests/test_scipy.py

👋 This adds the survival function and log survival function to the scipy.norm module. I needed it for one of my packages, and implemented it locally. However, others would like this too, so I'm adding it back to autograd.

adding survival function & log survival function for normal dist

---

.travis.yml
tests/test_direct.py
tests/test_fft.py
tests/test_graphs.py
tests/test_linalg.py
tests/test_logic.py
tests/test_tests.py

Convert testing to pytest from nose.

TEST: change to pytest 4.0+

---

docs/tutorial.md

Added link to Matthew's Deep Learning Summer School lecture, which I found very helpful.

Link to Deep Learning Summer School Lecture

---

autograd/numpy/numpy_jvps.py
autograd/numpy/numpy_vjps.py

x ** y have been already computed in ans, which can be replaced

Update vjp and jvp of power

---

autograd/numpy/linalg.py
tests/test_linalg.py

Implement the vjp of general eigen decompositions based on https://arxiv.org/pdf/1701.00392.pdf Eq(4.77). Also see discussions [here](https://github.com/tensorflow/tensorflow/pull/33808)

Add reverse mode AD for np.linalg.eig

---

autograd/numpy/numpy_boxes.py
autograd/numpy/numpy_vspaces.py

added float128, complex256 dtypes to numpy vspaces and boxes for #590

added float128, complex256 dtypes to numpy vspaces and boxes for #590

---

README.md

Closes #474. The numerical value being returned has been updated as well, and the graph is generated correctly.

Update `tanh` derivative README example

---

license.txt

Yearly copyright bump. Padding my changed LOC! 😛

Update license.txt, fix copyright license year

---

autograd/wrap_util.py

[Fix] Replace finally statement by except BaseException to suppress all exceptions

---

noxfile.py
tests/test_wrappers.py

Skip `test_dtypes` for now
