autograd/grads.py, autograd/node_types.py
Importing autograd had side-effects on the `operator` module that I think were unnecessary. This PR removes that side-effect and edits `node_types.py` to import `grads.py` directly. All the tests seem to pass with this change.
=> remove side-effects on operator module

autograd/numpy/numpy_extra.py
This test fails on master:
```python
import autograd.numpy as np
from autograd import grad
def f(J,h):
return -0.5*np.log(np.linalg.det(J)) + 0.5*np.dot(h,np.linalg.solve(J,h))
h = np.zeros(3.)
print grad(f)(-0.5*np.eye(3),h)
```
with an error like this
```
/Users/mattjj/Code/autograd/autograd/numpy/numpy_extra.py in primitive_sum_arrays(*arrays)
117             new_array[array.idx] += array.val
118         else:
--> 119             new_array += array
120     return new_array
121 primitive_sum_arrays.gradmaker = lambda *args : lambda g : g
ValueError: non-broadcastable output operand with shape () doesn't match the broadcast shape (3,3)
```
This commit attempts a very basic patch where it replaces that line of `primitive_sum_arrays` with a try/catch block that falls back to `new_array = …
=> array promotion failure in primitive_sum_arrays

autograd/core.py
This commit separates the forward and backward passes into functions. This change could make it [easier to evaluate Jacobians with a single forward pass](https://github.com/HIPS/autograd/blob/8ba4db62dc11b8dc6dd947864d63caad40c77256/autograd/convenience_wrappers.py#L47-48) (making them ~2x faster) and to make other additions that require access to the forward-pass-generated expression graph. It also makes the code a little more readable.
=> separate forward and backward pass functions

autograd/numpy/linalg.py, tests/test_linalg.py
This doesn't work:
```python
import autograd.numpy as np
from autograd import grad
np.random.seed(0)
def f(A):
return np.dot(b,np.linalg.solve(A,b))
def f2(A):
return np.dot(b,np.dot(np.linalg.inv(A),b))
A = np.random.randn(2,2)
b = np.random.randn(2)
print f(A)
print f2(A)
print
print grad(f)(A)
print grad(f2)(A)
```
It prints this:
```
3.37428091778
3.37428091778
-2.54701989
[[-1.85497949  1.43978617]
[ 0.89160513 -0.69204039]]
```
The latter is correct. The former doesn't even have the right dimension!
The problem is that the transposes used in [the gradient of `solve`](https://github.com/HIPS/autograd/blob/512506cc416516fb4e6c94babbcfb513f1b6bf9e/autograd/numpy/linalg.py#L15) are no-ops when applied to proper 1D vectors.
I think this pull request is a fix: it just adds calls to …
=> grad of np.linalg.solve can break from dimension-promotion problems

autograd/numpy/numpy_grads.py, tests/test_systematic.py
gradient for einsum with calling convention "einsum(op0, sublist0, op1, sublist1, ..., [sublistout])", which I wound up needing for a project I'm working on.
Unfortunately it fails when sublistout contains a repeated index. But the implementation of the more common convention "einsum(subscripts, *operands)" also suffers from the same problem.
=> einsum with alternate calling convention

autograd/numpy/numpy_grads.py
There is a minor bug in the numpy_grads.unbroadcast function due to the fact that array shapes are compared with the "is" operator instead of "==".  The former treats some dimensions as different that should actually be the same:
In [325]: 1 is 1L
Out[325]: False
In [326]: 1 == 1L
Out[326]: True
This caused assertion failures on line 351 for me and is the likely cause of #33 .
=> Fixed integer comparison in unbroadcast

autograd/numpy/numpy_extra.py
I'm not sure if this breaks anything.  All tests pass and it's confusing to have no dtype attached to these nodes.
=> Adding dtype to autograd nodes

autograd/container_types.py
Check this out:
```python
from autograd import grad
def f(tup):
a, lst = tup
x, y = lst
return a+x+y
print grad(f)((1.,[2.,5.]))  # prints (1.0, [1.0, 1.0, 0.0, 0.0])
```
On the current master (3836fc2) that prints `(1.0, [1.0, 1.0, 0.0, 0.0])`, but I think it should print `(1.0, [1.0, 1.0])`.
I think the problem is essentially that the primitive sum functions for container types, like `primitive_sum_tuples`, don't recursively call other primitive sum functions, like `primitive_sum_lists`, and instead they just call regular `sum`, leading to the list concatenation above. 
One way to fix it, which this PR attempts, might be to make the primitive_sum functions recursively call a primitive summer that can handle all containers as well as non-containers.
All the tests pass on this branch, and …
=> add recursive call to primitive_sum in container type sums

autograd/core.py, autograd/numpy/numpy_grads.py, tests/test_logic.py
We want Nodes to inherit the falseyness of their underlying values so that boxed values can be used in Python logic.
There was a certain pathology that could arise here when a numpy boolean-valued function was wrapped as primitive but didn't have a gradient implemented. The pathology would happen with a function like this one:
```python
def foo(x):
if np.isscalar(x):  # gradient of np.isscalar isn't implemented in current master
return x**2
else:
return np.sum(x)
grad(foo)(np.array([1., 2.]))  # does the wrong thing!
```
The problem is that np.isscalar(x) returns a Node wrapping the underlying False value, and since Python's default is to treat any object without a `__nonzero__` or `__bool__` as True, the forward execution is wrong. This problem won't happen when the function has a zero …
=> make Node have same falseyness as underlying value

autograd/numpy/linalg.py, autograd/numpy/linalg_extra.pyx, tests/test_linalg.py
I think the cholesky gradient is not quite the one we want. It agrees with the numerical gradient, but that numerical gradient is always lower-triangular (with zeros on the strict upper triangle) because the cholesky routine only reads the lower triangle of its input matrix. 
Here are two routines for computing log det on positive definite matrices via the cholesky decomposition. The correct gradient is matrix inverse:
```python
def plogdet(X):
L = np.linalg.cholesky(X)
return 2*np.sum(np.log(np.diag(L)))
def symmetrized_plogdet(X):
L = np.linalg.cholesky((X + X.T)/2.)
return 2*np.sum(np.log(np.diag(L)))
def rand_psd(n):
temp = np.random.randn(n, n)
return np.dot(temp, temp.T)
X = rand_psd(3)
print grad(plogdet)(X)
print grad(symmetrized_plogdet)(X)
print np.linalg.inv(X)
```
It prints …
=> explicitly symmetrize cholesky gradient

autograd/numpy/numpy_grads.py, tests/test_numpy.py, tests/test_systematic.py
Added a gradient for `np.tile` and support for calls to `np.sum` where the axis argument is a tuple, like `np.sum(x, axis=(0,1))`.
I made this a PR so travis will tell me if Python3 works.
=> add gradient for np.tile, add support for sum axis tuple

conda_recipe/conda.yaml
This PR adds the ability to build conda packages for https://anaconda.org. Since autograd is pure Python, this is really easy.
Uploading to Anaconda.org
-------------------------
Start with the commit checked out which was tagged with the new version. If conda.yaml has a hard-coded version, the version change should already be committed.
1. ``rm /path/to/anaconda/conda-bld/linux-64/autograd-*.tar.bz2`` on Linux/OSX (use ``del`` and correct path on Windows)
2. ``rm -R dist/*`` on Linux/OSX or ``del dist/*`` on Windows
3. ``conda build --python 2.7 conda_recipe/``
``conda build --python 3.3 conda_recipe/``
``conda build --python 3.4 conda_recipe/``
``conda build --python 3.5 conda_recipe/``
4. ``conda convert --platform all /path/to/anaconda/conda-bld/linux-64/autograd-*.tar.bz2 -o ./dist`` …
=> BLD: conda recipe for anaconda.org support

autograd/core.py
Some callables do not have a `__name__` attribute, for example those returned by functools.partial (see [here](http://stackoverflow.com/questions/33576932/do-all-callables-have-name)). Using `getattr(fun, '__name__', '[unknown name]')` instead of just `fun.__name__` prevents an `AttributeError` being thrown when attaching  `__name__` and `__doc__` in this case.
=> Add fallback when function missing __name__ attribute

examples/bayesian_neural_net.py, examples/bayesian_optimization.py, examples/convnet.py, examples/data.py, examples/data_mnist.py, examples/hmm_em.py, examples/ica.py, examples/neural_net_regression.py
I modified examples to support Python 3.x.
This fixes https://github.com/HIPS/autograd/issues/121 .
I also copied https://raw.githubusercontent.com/HIPS/Kayak/master/examples/data.py 
to examples/data_mnist.py and modified to support Python 3.x.
To run examples/bayesian_optimization.py on Python 3.x, you need another modification,
and I sent it in another pull request https://github.com/HIPS/autograd/pull/124 .
=> Examples Python 3.x support

autograd/numpy/numpy_grads.py
This pull request makes 2D 2D ```matmul``` 12 times faster by this benchmark.
https://gist.github.com/yukoba/719acfc489018b189840a0b1d9904d83
The current NumPy implementation of ```matmul``` and ```tensordot``` are
- without broadcasting: Use BLAS and fast.
- with broadcasting: Do not use BLAS and slow.
```einsum``` is
- Always do not use BLAS and slow.
My original Autograd 2D 2D ```matmul``` uses ```einsum```.
But I changed it to use none broadcasting ```tensordot```.
=> matmul speed up to use BLAS in 2D 2D matmul

autograd/scipy/stats/multivariate_normal.py, examples/gaussian_process.py
I added allow_singular and default values to multivariate_normal.
This is necessary to run examples/bayesian_optimization.py on Python 3.x.
=> Add allow_singular and default values to multivariate_normal

autograd/core.py
There should be a space here. I thought I might have introduced this typo but looks like it was there already.
=> Fix typo in attach_name_and_doc

examples/convnet.py, examples/data.py
Sorry, I forget to remove ```import imp``` from examples.
This is unnecessary because I created examples/data_mnist.py.
=> Remove unnecessary import imp

autograd/numpy/numpy_extra.py
numpy.add.at is slow (https://github.com/numpy/numpy/issues/5922); this change uses += instead, as long as we can be sure (?) that no element is indexed more than once. This speeds up my toy example by about 40%.
=> Use a[idx] += b instead of numpy.add.at(a, idx, b)

autograd/numpy/linalg.py, tests/test_linalg.py
See [here](https://j-towns.github.io/papers/svd-derivative.pdf) for a fairly complete derivation. Note that the derivation in the [Mike Giles paper](http://arxiv.org/abs/1602.07527) is missing the terms which I denote dK and is therefore not correct. A few points:
* The svd is not quite unique (multiplying a column of U and the corresponding column of V by -1 still gives a valid svd), and therefore its Jacobian is not unique either, and what the user gets is the Jacobian of the branch of the svd that they are on (hope that makes sense). I believe this is the same for `eigh` since multiplying one of the eigenvectors by -1 still gives a correct eigenvector.
* If `full_matrices=True`, then I think this non-uniqueness gets a lot worse, and I haven't yet tried to work out if it's still …
=> Implement svd gradient

examples/natural_gradient_black_box_svi.py
Hey DDM,
I've been playing around a bit with natural gradient methods for BBVI, and in my enthusiasm I made an autograd example.  This example uses the function from `examples/black_box_svi.py`, defines the Fisher for this parameterization of a diagonal Gaussian, and compares optimization between standard (using adam) and natural gradients (using momentum-less sgd) at different step sizes.  The resulting iteration vs. ELBO values are plotted at the end --- which looks like this for me:
I used a higher dimensional posterior (~40 dimensions) to highlight the differences. Let me know what you think!
-Andy
=> added natural gradient example

autograd/container_types.py, autograd/core.py, autograd/numpy/numpy_extra.py, autograd/numpy/numpy_grads.py, autograd/util.py, tests/test_forward.py
Now forward mode derivative calculations take place during forward calculation. The compositions fwd(fwd(fun)), rev(rev(fun)) and rev(fwd(fun)) are all behaving correctly, however fwd(rev(fun)) is giving incorrect answers for some reason.
=> Forward mode

.travis.yml
Tests all seem to run fine in Python 3.5 on my computer, I don't have Python 3.4 but I would guess they would also run fine...
=> Include Python 3.4+ in .travis.yml

setup.py
Hi,
I removed the setup_requires parameter in setup.py, which forced to have both numpy and scipy installed before installing autograd (and all packages that have autograd as a dependency). Running
`pip install autograd`
would fail in a clean environment, now it works fine.
Hope this helps!
=> Removed setup_requires parameter in setup.py

autograd/errors.py
`map(...).index()` doesn't work on Py3, just use a list comprehension
instead.
=> Fix map() usage on Py3.

autograd/convenience_wrappers.py, tests/test_wrappers.py
Also add test for grad of partial, fix typo in attached docstring and add fullstop to the end of attached docstring. Fixes https://github.com/HIPS/autograd/issues/167.
=> Workaround for partial __name__

examples/convnet.py, examples/fluidsim/wing.py, examples/mixture_variational_inference.py, examples/variational_autoencoder.py
This means you don't get the following warning when running them:
```
VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
```
=> Use integers for array indexing in examples

autograd/convenience_wrappers.py, tests/test_wrappers.py
Support for different float dtypes, such as float32 and float16. Automatically infer the correct dtype. This is handy because the smaller floats use less memory and are faster. Fixes https://github.com/HIPS/autograd/issues/163.
=> Dtype support

autograd/numpy/numpy_grads.py
This PR simplifies the implementation of `repeat_to_match_shape` to use numpy broadcasting and `vs.zeros()`.
Let me know if you see any problems with this approach. Otherwise I'll merge it at some point in the next few days.
=> simplify repeat_to_match_shape using vs.zeros()

examples/data.py
I get an error when running the variational_autoencoder.py example (and probably other examples which call the `plot_images` function from data.py). This is caused by trying to use a float as part of a shape tuple. Line 28 of data.py is
```
N_rows = np.ceil(float(N_images) / ims_per_row)
```
This creates a float (np.ceil returns a float), which is then used here in a shape parameter a couple of lines below:
```
concat_images = np.full(((digit_dimensions[0] + padding) * N_rows + padding,
(digit_dimensions[1] + padding) * ims_per_row + padding), pad_value)
```
This is trivial to fix...
=> Fix float shape parameter in data.py

.travis.yml
Also switch default package source to the open source 'conda-forge' channel, which fixes the testing issue with [https://github.com/HIPS/autograd/pull/213](https://github.com/HIPS/autograd/pull/213).
=> Add Python 3.6 to travis testing

autograd/numpy/numpy_grads.py, setup.py, tests/test_systematic.py
Our current `grad_einsum` implementation relies on some manual string parsing, which doesn't handle all cases (e.g. `np.einsum('k,nk->', randn(2), randn(3,2))` caused an einsum subscript error, and `np.einsum('ij,k', randn(2, 3), randn(4))` caused a NotImplementedError).
This PR replaces that manual string parsing with a call to the new `_parse_einsum_input` function in numpy 1.12, simplifying and generalizing `grad_einsum` at the cost of bumping the numpy version requirement and relying on an internal numpy function. We could instead get the same function from the [opt_einsum module](https://github.com/dgasmith/opt_einsum), or we could copy its source into autograd (if the licenses allow) since it's short and self-contained.
Now we don't even need to call `unbroadcast_einsum` when using …
=> simplify and generalize grad_einsum by using numpy's new _parse_einsum_input

autograd/core.py
Attempting to help issues mentioned in https://github.com/HIPS/autograd/issues/219
This line removed any references to Array nodes which will not be revisited, since they have passed all their gradient information to their parents.
In the special case of the start_node, the gradients will not be lost, since setting outgrads[node] to None only deletes the reference, not the values. So as long as cur_outgrad holds on to the gradient reference all is fine.
On a test dataset, using a proprietary algorithm which can be roughly described as two RNN's feeding into eachother, I obtained the following gains in performance.
https://cloud.githubusercontent.com/assets/6620250/25814415/6a8f085a-33eb-11e7-9237-ce58fa09300a.png
In addition, I compared the numerical results of my change to the previous …
=> backward_pass now clears nodes which will not be used

examples/variational_autoencoder.py
A very minor point... `objective` is already a scalar, so taking its mean here does nothing.
=> Remove unnecessary mean from vae example

examples/variational_autoencoder.py
The 'unnormalised probability' is (I think) the log-odds or logit
x = log(p / (1 -  p) )
To recover p I think we need
p = 1/(1 + e^{-x})
&nbsp;&nbsp;&nbsp;= 0.5 * (tanh(0.5 * x) + 1).
Note that both of these functions are included as ufuncs in scipy.special: [logit](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.logit.html#scipy.special.logit), [sigmoid (AKA expit)](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.expit.html#scipy.special.expit). So maybe at some point we should implement their gradients and start using them as primitives.
=> Another small correction to vae example

autograd/container_types.py, autograd/numpy/numpy_extra.py, autograd/util.py, benchmarks/benchmarks.py
Use the vspace flatten functionality for util.flatten. This enables flattening of complex values which wasn't previously possible.
Am I missing some reason why this isn't ok? The only difference in functionality which I can see is that with this change, calling `flatten` on scalars will give an `unflatten` which returns scalar values _wrapped in an array_. In particular:
**On master**
```python
In [1]: from autograd.util import flatten
In [2]: v, unflatten = flatten(3.)
In [3]: v
Out[3]: array([ 3.])
In [4]: unflatten(v)
Out[4]: 3.0
```
**With this change:**
```python
In [1]: from autograd.util import flatten
In [2]: v, unflatten = flatten(3.)
In [3]: v
Out[3]: array([ 3.])
In [4]: unflatten(v)
Out[4]: array(3.0)
```
Is this a big deal? This type of behaviour occurs in other situations …
=> Simplify util.flatten

autograd/numpy/numpy_grads.py
I believe this is unnecessary since https://github.com/HIPS/autograd/commit/c1463efc152a0896ffbdf150ffcaa92d957690c9
=> Remove unnecessary section of unbroadcast_einsum

autograd/convenience_wrappers.py, autograd/core.py, autograd/numpy/numpy_extra.py, tests/test_complex.py, tests/test_graphs.py
Add `vspace.ones()` and `vspace.standard_basis()`, for use in `grad` and `jacobian` to reduce the dependence of core.py on numpy, and also to simplify the code.
This PR also currently includes a change in the behavior of `grad` on non-scalar-valued functions. In master, when `grad` is applied to non-scalar-valued functions, it raises an error. To get broadcasting support, we use a separate function `elementwise_grad`. The change in behavior here is that `grad` now acts like `elementwise_grad` on non-scalar-valued functions, instead of raising an error. I think the error raising behavior would be easy to restore by adding a check on the output vspace, but this change seems worth considering.
=> vspace ones and standard_basis methods

autograd/__init__.py, autograd/convenience_wrappers.py, autograd/core.py, tests/test_wrappers.py
This PR adds the `make_jvp` and `make_ggnvp` convenience wrappers we developed in the thread for #175, plus tests. (It also adjusts the names inside make_vjp to be more consistent with vjp usage elsewhere.)
There are some wasted FLOPs in these implementations where we propagate zero vectors through vjp's just to trace them; I think we could get rid of these wasteful computations by adding a new function to core.py that essentially transposes the matrix-free linear map represented by calling `backward_pass` on a trace. However, there would still be graph munging overhead compared to a proper forward-mode implementation.
=> Add make_jvp and make_ggnvp convenience wrappers

README.md, examples/tanh.py
We recently changed `grad` to handle broadcasting automatically. This PR updates README.md accordingly, and also changes examples/tanh.py to explain this behavior in a bit more detail.
=> change readme not to use elementwise_grad, since grad now broadcasts

examples/convnet.py
The previous code for the max pool layer was implemented along the wrong directions.  Even though the global shape of the resulting array was correct, its content was completely off.  This can easily be seen by looking at some plots of before and after the max pool layer.
This pull request fixed this bug so that the max pool layer is now correctly implemented.
=> fixed reshape bug in maxpool layer of convnet example

examples/variational_autoencoder.py
The third parameter of `diag_gaussian_log_density` is `log_std` — the log of the standard deviation. The prior p(z) should have standard deviation 1, the log of this is 0, not 1.
=> Fix vae example latent probability

examples/variational_autoencoder.py
This seems to improve performance a bit. On master
```
%timeit objective_grad(combined_init_params, 0)
102 ms ± 4.16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
and with this change
```
%timeit objective_grad(combined_init_params, 0)
68.9 ms ± 1.38 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
=> Use expit for sigmoid in vae example

autograd/core.py
I can't see what situation this line is checking for. Removing it doesn't cause any of the tests to fail. Note that if the check were ever relevant, then with it removed the line below:
```python
cur_outgrad = outgrads.pop(node)
```
would throw an exception, which doesn't happen in any of the tests.
I've also run the benchmarks comparing this commit to master, and it doesn't produce any significant changes.
=> Remove seemingly unnecessary outgrad check

.travis.yml, autograd/numpy/linalg.py, setup.py, tests/test_linalg.py, tests/test_scipy.py
The Travis CI tests pass both with and without scipy installed (where it skips scipy tests, printing a warning, if scipy isn't installed).
There might be a cleaner way to implement this than the try/except/else mechanism in tests/test_scipy.py, but this approach seems alright for now.
=> organize code and travis to remove scipy dependence

autograd/numpy/numpy_vjps.py
Now the tests fail when vs.ndim is incorrect as it was prior to 75c0254bfe318cd66b2ee3793ac14d6ceb94e3cc
=> Use vs.ndim in unbroadcast

autograd/core.py
Is there any reason not to write the vspace check this way?
=> tweak backward_pass vspace check to be fewer characters

autograd/numpy/numpy_jvps.py, autograd/numpy/numpy_vjps.py, benchmarks/bench_numpy_vjps.py, tests/test_systematic.py
I've given tensordot the adjoint treatment, and this seems to have improved performance (though not as dramatically as for dot):
```
before     after       ratio
[4e517a01] [82068d0e]
-  366.45μs   241.00μs      0.66  bench_numpy_vjps.time_tensordot_1_0
-  380.09μs   238.82μs      0.63  bench_numpy_vjps.time_tensordot_1_2
-  379.86μs   236.12μs      0.62  bench_numpy_vjps.time_tensordot_1_1
```
There should also be a good knock on effect for primitives like inner and matmul which use these adjoints as their derivatives.
By the way, I just noticed that [from Numpy 1.4 Einsum is going to use the parallelized BLAS dot routine when possible](https://github.com/dgasmith/opt_einsum#news-opt_einsum-will-be-in-numpy-112-and-blas-features-in-numpy-114-call-opt_einsum-as-npeinsum-optimizetrue-this-r …
=> Tensordot adjoints

autograd/container_types.py, autograd/convenience_wrappers.py, autograd/core.py, autograd/numpy/fft.py, autograd/numpy/linalg.py, autograd/numpy/numpy_jvps.py, autograd/numpy/numpy_vjps.py, autograd/numpy/numpy_wrapper.py, autograd/scipy/linalg.py, autograd/scipy/misc.py, autograd/scipy/signal.py, autograd/scipy/special.py, autograd/scipy/stats/dirichlet.py, autograd/scipy/stats/multivariate_normal.py, autograd/scipy/stats/norm.py, autograd/scipy/stats/t.py, autograd/test_util.py, autograd/vspace.py, tests/test_tests.py
These commits make vspaces optional in many parts of the code, and in particular remove them from the VJP signatures. The main motivation is to minimize computational overhead. (We might want to add back some assert statements at some point, since those can be excised from the code easily with zero runtime overhead.)
=> Experiment no vspace checks

benchmarks/bench_core.py, benchmarks/bench_numpy_vjps.py, setup.py
I've added some temporary scaffolding to the benchmarks so that they'll run on both master and dev-1.2. I've run a comparison on an AWS instance, the results are:
```
[master]  [dev-1.2]
-----------------
VSPACE
-----------------
-    2.32μs     1.97μs      0.85  bench_core.time_vspace_float
-    2.29μs     1.97μs      0.86  bench_core.time_vspace_array
-----------------
FLATTEN
-----------------
+  215.12μs     2.19ms     10.18  bench_util.time_flatten
+  665.45μs     3.25ms      4.89  bench_util.time_grad_flatten
-----------------
PRIMITIVE CALL
-----------------
+    1.06μs     1.22μs      1.15  bench_core.time_exp_call
-    3.23μs     2.76μs      0.86  bench_core.time_exp_primitive_call_unboxed
+    3.95μs    10.37μs      2.63  bench_core.time_exp_primitive_call_boxed …
```
=> Bench compatibility

autograd/misc/flatten.py
=> Correct indentation in flatten.py

.travis.yml
This way tests will fail if for example not all sub-packages have been installed. This is pretty important, tests should certainly fail if we're not even installing the whole of Autograd.
Note that tests fail due to an import error on this branch (as they should), merging https://github.com/HIPS/autograd/pull/294 will fix this.
=> Have travis move into tests folder

autograd/builtins.py, autograd/core.py, autograd/extend.py, autograd/numpy/numpy_jvps.py, autograd/numpy/numpy_vjps.py, autograd/numpy/numpy_wrapper.py, autograd/tracer.py
I'm playing around with how we can make trace-dropping logic conditional on the trace type. The main change here is in tracer.py:`primitive`.
We could tweak this implementation a bit to get back the drop-parent-on-zero-vjp behavior: basically in `primitive` we could filter the parents/argnums lists according to some trace-type-specific side information (like the current `notrace_primitives[node_constructor]` set), then only create a new box if the parents list is nonempty.
There are a couple unrelated changes here in builtins.py to do with adding methods to those Box types.
I ran `asv continuous dev-1.2 experiment-conditional-notrace` and didn't see any significant changes. (I ran it twice and each time there were a couple of minor changes, but they were different across the two runs, so …
=> Experiment with conditional notrace logic

autograd/scipy/stats/__init__.py, autograd/scipy/stats/poisson.py, tests/test_scipy.py
This PR implements VJPs for the Poisson CDF and PMF w.r.t. the rate parameter (`mu` in SciPy).
=> Implement VJPs for Poisson CDF and PMF

autograd/scipy/special.py, tests/test_scipy.py
This PR implements VJPs for the regularized lower and upper incomplete gamma functions w.r.t. the limit of integration (`x` in SciPy).
=> Implement VJPs for incomplete gamma functions

autograd/builtins.py, tests/test_dict.py, tests/test_list.py, tests/test_tuple.py
As a result, users can write code like this:
```python
from autograd.builtins import list
...
assert isinstance([], list)
```
without having to keep autograd's `autograd.builtins.list` separate (since `isinstance([], autorad.builtins.list)` is `False` before this commit, but `True` now).
I think this is basically [Python's intended use case for overriding these methods in the metaclass](https://docs.python.org/2/reference/datamodel.html#customizing-instance-and-subclass-checks).
=> Add metaclasses so that more isinstance checks work.

autograd/scipy/stats/__init__.py, autograd/scipy/stats/chi2.py, tests/test_scipy.py
This PR implements VJPs for the χ² CDF and PDF w.r.t. its argument (`x` in SciPy).
=> Implement VJPs for χ² CDF and PDF

autograd/scipy/stats/__init__.py, autograd/scipy/stats/gamma.py, tests/test_scipy.py
This PR implements VJPs for the gamma PDF w.r.t. its argument and shape parameter (`x` and `a` in SciPy, respectively).
=> Implement VJPs for gamma CDF and PDF

.travis.yml
An easy fix for the Travis build errors we're currently getting, which are caused by a dependency not supported on 3.4 and 3.5.
=> Only travis test Python 2.7 and 3.6

autograd/numpy/numpy_vjps.py, tests/test_systematic.py
This resolves https://github.com/HIPS/autograd/issues/350. I could have implemented the grad of rollaxis for negative args, however was put off by its nastiness (the `start` arg doesn't have the usual axis bounds - it can be equal to ndim which is quite weird). Indeed in the [new Numpy (1.14) doc for rollaxis](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.rollaxis.html), it says
> This function continues to be supported for backward compatibility, but you should prefer `moveaxis`. The `moveaxis` function was added in NumPy 1.11.
So I hope you're ok with this fix.
=> Raise NotImplementedError on negative rollaxis args

autograd/test_util.py
Have now realised the output order was actually correct because the variables were incorrectly swapped round twice, meaning they ended up back in the right place.
=> Correct exact/numeric vjv variable naming in check_vjp

autograd/differential_operators.py, tests/test_wrappers.py
Figured this trick out whilst writing the code for https://github.com/HIPS/autograd/issues/339.
**TODO:**
=> Simplify grad_and_aux

autograd/scipy/__init__.py, autograd/scipy/integrate.py, tests/test_scipy.py
This pull request adds the gradient of odeint with respect to the initial state, initial and measurement times, and the parameters of the dynamics.
Potential gotcha: Since odeint requires the args of the dynamics to be in a tuple, one has to use autograd.tuple if you want to differentiate wrt to args.
Room for improvement: Right now all derivatives are computed, even if only one is asked for.  This can require solving a larger system than necessary.  One could also implement all 7 combinations of possible derivatives and be a bit more efficient at the expense of duplicated code.
=> Added gradients for scipy.integrate.odeint

autograd/scipy/stats/multivariate_normal.py, tests/test_scipy.py
This pull request adjusts the vjp for the multivariate normal covariance parameter, which was returning gradients with the wrong sign. It seems that a small typo in the unit test script had been preventing the tests for these vjps from running, which is probably why this wasn't picked up earlier. Resolves issue #401 .
=> Fix vjp for multivariate normal covariance

autograd/numpy/linalg.py, tests/test_linalg.py
This is a replacement for pull request https://github.com/HIPS/autograd/pull/383.
It adds a test that passes. Good thing the other pull request (without a test) wasn't accepted. It was wrong for non-square, symmetric matrices.
=> Added derivative for numpy.linalg.pinv() with a test (that passes).

autograd/numpy/numpy_vjps.py, tests/test_systematic.py
The tensordot vjps did not handle axis specification correctly. This should be fixed here, including a test that failed in before the fix.
=> fix issue 446: tensordot vjps not handling axes specification correctly

autograd/numpy/numpy_jvps.py, autograd/numpy/numpy_vjps.py, autograd/numpy/numpy_wrapper.py, tests/test_numpy.py, tests/test_systematic.py
I've implemented a VJP for `numpy.gradient`. The function `numpy.gradient` itself is wrapped in `autograd.numpy` and only accepts the `axis` keyword. 
ATM only first order diff works due to the manual assignment in the VJP (see e.g. `numpy_vjps.py:212`).
=> Add VJP for numpy.gradient

autograd/scipy/misc.py, autograd/scipy/special.py, docs/tutorial.md, examples/define_gradient.py, examples/gmm.py, examples/hmm_em.py, examples/lstm.py, examples/mixture_variational_inference.py, examples/neural_net.py, examples/rnn.py, tests/test_scipy.py
I am building a project using `autograd`, and using `autograd.scipy.misc.logsumexp` emits a warning. This is a tiny thing, since it is suppressed normally, unless you pass a flag, or are using `autograd` with `pytest`.
You can see the warning by starting python with `python -Wall`, and running
```python
from autograd.scipy.misc import logsumexp
logsumexp([1])
/home/projects/autograd/autograd/tracer.py:48: DeprecationWarning: `logsumexp` is deprecated!
Importing `logsumexp` from scipy.misc is deprecated in scipy 1.0.0. Use `scipy.special.logsumexp` instead.
return f_raw(*args, **kwargs)
1.0
```
This is the smallest, easiest way to make the fix -- I am also happy to follow the scipy path (so `from autograd.scipy.misc import logsumexp` emits a warning, but `from autograd.scipy.special import …
=> Fix scipy deprecation warning

autograd/numpy/fft.py, autograd/numpy/numpy_vjps.py, autograd/scipy/signal.py, autograd/scipy/stats/multivariate_normal.py
Fixes #468. 
There is still a numpy warning about converting complex to real, and tests show a bunch of `UserWarning: Output seems independent of input` from `tracer.py`.
=> MAINT: fix numpy warnings, mainly by converting to tuple

benchmarks/bench_core.py
It seems benchmarks were not updated for a change in `VJPNode.initialize_root`. Steps to reproduce
- clone the repo
- cd into `benchmarks`
- run `python3 -masv run --config asv.conf.json.sample`
The last step fails before this PR, succeeds after.
If I am doing something wrong, perhaps this PR should be pivoted to a documentation issue, where a short README.md in this directory would be helpful
=> BENCH: fix benchmarks for initialize_root()

autograd/numpy/numpy_wrapper.py
Fixes #398 
With this and #507 I can run benchmarks with pypy and python3
```
python -m asv run --config asv.conf.json.sample --python=pypy3 pypy~1..pypy
python -m asv run --config asv.conf.json.sample --python=3.6 pypy~1..pypy
```
and (after adding this branch to the `branches` key in the config file) view the results with
```
python -m asv publish --config asv.conf.json.sample
python -m asv preview --config asv.conf.json.sample
```
Unfortunately, asv is not really set up to `compare` across pythons (see airspeed-velocity/asv#789 which I think helps) so I needed to use the web framework to be able to compare. While PyPy is slower at most benchmarks, for some it gives a noticable speedup.
=> ENH: fix wrapper for pypy

autograd/numpy/linalg.py
Use ==/!= to compare str, bytes, and int literals.
$ __python__
```
>>> ord = 'fr'
>>> ord += 'o'
>>> ord == 'fro'
True
>>> ord is 'fro'
False
```
[flake8](http://flake8.pycqa.org) testing of https://github.com/HIPS/autograd on Python 3.7.1
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./autograd/numpy/fft.py:19:8: F821 undefined name 'fft'
defvjp(fft, lambda *args, **kwargs:
^
./autograd/numpy/fft.py:20:32: F821 undefined name 'fft'
fft_grad(get_fft_args, fft, *args, **kwargs))
^
./autograd/numpy/fft.py:21:8: F821 undefined name 'ifft'
defvjp(ifft, lambda *args, **kwargs:
^
./autograd/numpy/fft.py:22:32: F821 undefined name 'ifft'
fft_grad(get_fft_args, ifft, *args, **kwargs))
^
./autograd/numpy/fft.py:24:8: F821 undefined name 'fft2'
defvjp(fft2, lambda …
```
=> Identity is not the same thing as equality in Python

autograd/numpy/linalg.py, tests/test_linalg.py
*Edit: as discussed in the comments below, the issue with the complex eigenvectors is the gauge, which is arbitrary. However, this updated code should work for complex-valued matrices and functions that do not depend on the gauge. So for example, the test for the complex case uses `np.abs(v)`.*
What this update does:
- fix the vjp computation for numpy.linalg.eigh in accordance with the behavior of the function, which *always* takes *only* the upper/lower part of the matrix
- fix the tests to take random matrices as opposed to random symmetric matrices
- fix the computation to work for Hermitian matrices as per [this](https://github.com/HIPS/autograd/pull/462) pull request, on which I've built
However:
- the gradient for Hermitian matrices works only for the eigenvalues and not (always) …
=> Further correcting grad_eigh to support hermitian matrices and the UPLO kwarg properly

autograd/numpy/linalg.py
The version of grad_eigh used previously only supported real symmetric inputs to eigh.
Changing v to conj(v) in two places makes the function correct for arbitrary Hermitian 
matrices, not just real symmetric ones.
=> Correct grad_eigh to support hermitian matrices

autograd/numpy/linalg.py, tests/test_linalg.py
The original svd_grad function doesn't work for complex valued matrices. Have fixed it according to the discussion in https://github.com/tensorflow/tensorflow/issues/13641.
I will add more test.
=> Fix complex valued svd backpropagation.

autograd/differential_operators.py
Where `inspect.getfullargspec` is available (Python 3.0 and later), use it instead of `inspect.getargspec`, which was deprecated in Python 3.0 and will be removed in Python 3.11.
This change is necessary in order to make `autograd` compatible with Python 3.11. The conditional import can be dropped once Python 2.7 is no longer supported.
=> Replace inspect.getargspec on Python 3

autograd/builtins.py, autograd/numpy/numpy_boxes.py, autograd/numpy/numpy_vspaces.py
The functions in numpy.linalg which returned tuples in version <= 1.24 have switched to using a different NamedTuple type for each function. To support this I've added the necessary Box and VSpace registrations.
=> Add support for NamedTuples, support NumPy 1.25 (fixes #597)

.github/workflows/test.yml, tox.ini
Installing scipy with Pip requires a few prerequisites on the various target platforms. Alternatively, using Conda makes things easier. See [StackOverflow](https://stackoverflow.com/questions/26575587/cant-install-scipy-through-pip) for a related discussion.
This is a follow-up on #602.
=> Fix GHA pipeline, install scipy using conda

.github/workflows/test.yml, pyproject.toml, tox.ini
Installing extras via Conda while Tox would use Pip + virtualenv proves to be brittle. We'll factor `scipy` into the list of Tox environments instead, which will also make the test setup more straight-forward, less complex to understand and able to entirely run locally.
<details>
<summary>Tox environments available now (click to expand)</summary>
```console
$ tox list
default environments:
ruff          -> Lightening-fast linting for Python
py27          -> Unit tests and test coverage
py27-scipy    -> Unit tests and test coverage
pypy27        -> Unit tests and test coverage
pypy27-scipy  -> Unit tests and test coverage
py35          -> Unit tests and test coverage
py35-scipy    -> Unit tests and test coverage
py36          -> Unit tests and test coverage
py36-scipy    -> Unit tests and …
```
=> Install extras for testing via Tox, test with SciPy+PyPy only on Ubuntu

autograd/scipy/linalg.py, tests/test_scipy.py
Until now, autograd only handles scipy.linalg.solve() and scipy.linalg.solve_triangular().
In contrast to scipy.linalg.solve() and scipy.linalg.solve_triangular(); scipy.linalg.solve_banded() can handle VERY large systems of equations.
In fact, I think that solve_banded() could interest a lot of autograd users: banded systems are ubiquitous in ODEs, PDEs and signal processing.
Furthermore, solve_banded() could be of interest to a wider audience, since sparse matrix solvers are not handled yet by torch.autograd (to the best of my knowledge).
In that sense, solve_banded() would be a first step towards handling a specific subset of sparse matrices, namely  banded matrices.
Last but not least, I hope that, at a later stage, someone could then adapt, improve and include my code to …
=> add support of scipy.linalg.solve_banded()

README.md
I've been finding it very difficult to keep up with Autograd issues and maintenance in recent months, and have decided it's best to change the readme to reflect the fact that it is effectively unmaintained at the moment.
=> Announcing unmaintained status

.github/workflows/test.yml
This PR removes Python 3.7 from the CI as it reached it's end of life a year ago (and not all runners are still available in Github Actions). Python 3.8 will reached its EOL in three months so I would propose to support it until then.
=> [ci] Remove python 3.7 runners from test workflow.

.github/workflows/check.yml, .github/workflows/publish.yml, .github/workflows/test.yml, MANIFEST.in, autograd/builtins.py, autograd/numpy/numpy_vjps.py, autograd/scipy/signal.py, conda_recipe/conda.yaml, examples/data_mnist.py, pyproject.toml, tox.ini
- Stemmed off from #618 – the packaging infrastructure for `autograd` has been migrated to use `hatchling.build` instead of `setuptools.build_meta` as the build backend. Some missing metadata entries have been added in `pyproject.toml`.
- Dependence on the `six` and `future` libraries has been removed, since all of the code is compatible with Python 3.
- Python 2 support has been dropped and the wheels are tagged with `py3` for the Python tag instead of `py2-py3`.
- Lastly, I added some future TODOs so that I can keep track of them sometime soon.
Closes #606
Closes #513, since we won't need `setuptools`-specific files anymore.
- to enable VCS versioning via dynamic = ["version"] and the `hatch-vcs` plugin to derive the version from Git; and
- to use hatch environment commands in place of …
=> chore: migrate to hatch + use hatchling for the build backend, drop Python 2 support

tests/test_wrappers.py
In Python 3.13, the bytecode compiler now strips indentation from docstrings; see https://docs.python.org/3.13/whatsnew/3.13.html#other-language-changes.
Rather than conditionalizing based on the interpreter version, I adjusted the test to match the docstring with or without indentation.
After this PR, all tests pass in `tox -e py313`. I didn’t try `tox -e py313-scipy` since scipy doesn’t yet publish binary wheels for Python 3.13 and it is difficult to build from source.
=> Adjust test_wrapped_name_and_docs for Python 3.13

.github/workflows/publish.yml
Stemmed off from https://github.com/HIPS/autograd/pull/618. This updates the release workflow prior to triggering a new v1.7.0 release.
1. Better coloured output: `FORCE_COLOR:` environment variable set to `3`
2. Workflow will now not be triggered from a tag but from a GitHub Release made from said tag (gives better control in case a tag is created and pushed to GitHub in haste)
3. Uses `pypa/build` to build the sdist and then the wheel from the sdist
4. Some bumps to GitHub Actions versions
5. The build and upload steps are now isolated, sharing artifacts. They are integrated with varying permissions to enhance security in the advent of events from malicious actors. The PyPI upload step uses the environment set in the repository settings and trusted publishing has been set up by @j-towns …
=> chore: update the release workflow

autograd/numpy/numpy_wrapper.py
After the 1.7.0 release I noticed the following deprecation warning:
```
autograd/numpy/numpy_wrapper.py:7: DeprecationWarning: numpy.core.einsumfunc is deprecated and has been renamed to numpy._core.einsumfunc. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.einsumfunc._parse_einsum_input.
```
This PR simply replaces the import from `numpy.core.einsumfunc` by `numpy._core.einsumfunc` which should fix the warning but adds the risk …
=> [Fix] Fix numpy.core.einsumfunc deprecation

.github/workflows/test.yml
At least for now I think it can be useful to trigger the test pipeline automatically once every month to spot any problems. I also propose to add `workflow_dispatch` which allows us to manually trigger a run via the GitHub UI without having to push a commit.
=> [ci] Run test workflow at the beginning of every month and enable manual trigger of the pipeline.

autograd/numpy/numpy_boxes.py
Small change that adds the `__array_namespace__` method from the [Array API standard](https://data-apis.org/array-api/2022.12/API_specification/generated/array_api.array.__array_namespace__.html) to autograd's `ArrayBox`.
This makes autograd (partially) compatible with libraries that check for array API compatibility, such as [xarray](https://github.com/pydata/xarray), because xarray will coerce types that do not implement the array API into regular numpy arrays, see relevant discussion [here](https://github.com/pydata/xarray/issues/7848).
The following code snippet:
```python
import xarray as xr
import autograd.numpy as np
from autograd import grad
def f(x):
data = xr.DataArray(x, dims=range(x.ndim)).data
print(data)
return np.sum(data)
x = np.random.uniform(-1, 1, 10)
grad(f)(x)
``` …
=> Add `__array_namespace__` to `ArrayBox`

.github/workflows/test.yml, pyproject.toml
I was working on #643 and realised that we should now drop Python 3.8 since it has passed its EoL date, now. I also added Python 3.13 to the testing configuration here and updated the related metadata for this in `pyproject.toml`.
=> chore: drop Python 3.8 and start testing against Python 3.13

.github/workflows/test.yml, noxfile.py, tests/test_scipy.py
This PR enables testing against NumPy and SciPy nightlies, which were added in #632 and later disabled to be split out here. I've also fixed a test relating to incorrect shapes being cast (scalars were not being treated as arrays) within the `combo_check` function, so all tests should now pass on nightly and stable versions.
Related to #630
=> Fix `scipy.special.logsumexp` type promotion, test against NumPy and SciPy nightlies

pyproject.toml
This change is as discussed between @j-towns, @fjosw, and me; and subsequently posted publicly in https://github.com/HIPS/autograd/pull/643#issuecomment-2414374600. Pinning to NumPy <= 2.3 would also be an ideal option, but we have opted for a more relaxed pin to NumPy <3, owing to the fact that we have limited availability to add new features and hence fewer chances of anything major breaking.
This change should be merged after #643, and has been split from it because it is not directly related to the proposition of adding tests against nightly dependencies.
=> Pin to NumPy <3

autograd/scipy/__init__.py, autograd/scipy/misc.py, examples/fluidsim/fluidsim.py
With the latest scipy 1.15 release `scipy.misc` was deprecated which triggers a warning in autograd:
```
DeprecationWarning: scipy.misc is deprecated and will be removed in 2.0.0
import scipy.misc as osp_misc
```
We only use the misc module to provide `logsumexp` which has been moved to `scipy.special` many years ago, so removing the functionality should not change anything for users on python>=3.9.
I also changed the import in the fluidsim example ([imread](https://docs.scipy.org/doc/scipy-1.2.3/reference/generated/scipy.ndimage.imread.html#scipy.ndimage.imread) is deprecated in SciPy 1.0.0. Use matplotlib.pyplot.imread instead)
=> [Fix] Remove scipy.misc

.github/workflows/check.yml, .github/workflows/publish.yml, .github/workflows/test.yml
- Linux arm64 runners are now generally available for GitHub Actions usage.
- Pins all GitHub Actions used to their hashes instead of using their versions.
- https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
- https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions
=> Add Linux arm64 CI, pin GitHub Actions to hashes

.github/workflows/check.yml, .github/workflows/publish.yml, .github/workflows/test.yml
- PyPy is now available on the `ubuntu-22.04-arm` images
- PyPy has now dropped Python 3.9 since PyPy 7.3.17, see https://pypy.org/posts/2025/02/pypy-v7319-release.html
- ~PyPy's Python 3.11 can now be tested~ NumPy wheels for "pypy-3.11" are not available yet, so we should wait for this to happen.
=> Enable PyPy tests on Linux arm64, and remove `pypy-3.9`

autograd/numpy/__init__.py, autograd/numpy/numpy_wrapper.py, tests/test_numpy.py
Closes #679; `autograd.numpy.__version__` will now display the underlying NumPy version.
=> Export NumPy version from Autograd wrapper
